source 'https://cdn.cocoapods.org/'
platform :ios, '9.0'

target 'OCUIExample' do
  pod 'Masonry'
  pod 'CombineObjectObjc', :path => "./Pods/CombineObjectObjc/CombineObjectObjc.podspec"
  pod 'DriverListNode', :path => "./Pods/DriverListNode/DriverListNode.podspec"
end
